site_name: vicon_nexus_unity_stream_py
site_description: Python script to stream data from vicon nexus to unity
site_author: Ahmed Shariff

repo_url: https://github.com/ahmed-shariff/vicon_nexus_unity_stream_py
edit_uri: https://github.com/ahmed-shariff/vicon_nexus_unity_stream_py/edit/master/docs

theme: readthedocs

markdown_extensions:
  - codehilite

nav:
  - Home: index.md
  - Advanced: advanced.md
  - About:
    - Release Notes: about/changelog.md
    - Contributing: about/contributing.md
    - License: about/license.md
